#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'lbr-demos-fri-ros2-python==1.1.5','console_scripts','wrench_sine_overlay_node'
__requires__ = 'lbr-demos-fri-ros2-python==1.1.5'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('lbr-demos-fri-ros2-python==1.1.5', 'console_scripts', 'wrench_sine_overlay_node')()
    )
